"""
PFZ Intelligence & Ocean Analytics Data Schemas
ISRO SIH 2026 - Problem Statement 26176
Phase 6: PFZ Intelligence, Ocean Analytics & Environmental Hazard Fusion
"""

from enum import Enum
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field
from datetime import datetime, timezone

class PFZResultType(str, Enum):
    """
    Mandatory distinction between authoritative advisories and computed PFZs.
    Section 5 & Section 23 requirement.
    """
    OFFICIAL_PFZ = "OFFICIAL_PFZ"           # Authoritative external agency (e.g. INCOIS)
    MODEL_DERIVED_PFZ = "MODEL_DERIVED_PFZ" # Generated by ORCA's multi-variable EO analytics
    HISTORICAL_PFZ = "HISTORICAL_PFZ"       # Historical / archived candidate information
    UNAVAILABLE = "UNAVAILABLE"             # Data coverage or inputs insufficient

class EnvironmentalHazardStatus(str, Enum):
    """
    Multi-hazard context fusion classification.
    Section 16 requirement.
    """
    ENVIRONMENTALLY_FAVORABLE = "ENVIRONMENTALLY_FAVORABLE"
    ENVIRONMENTALLY_FAVORABLE_BUT_HAZARDOUS = "ENVIRONMENTALLY_FAVORABLE_BUT_HAZARDOUS"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    UNSUITABLE = "UNSUITABLE"
    UNAVAILABLE = "UNAVAILABLE"

class SuitabilityBreakdown(BaseModel):
    """
    Inspectable, transparent component scores and explicit weights.
    Section 11 requirement: A score of 0.86 must be explainable.
    """
    sst_suitability: float = Field(..., description="Thermal habitat optimality score (0.0 - 1.0)")
    sst_front_strength: float = Field(..., description="Thermal gradient frontal score (0.0 - 1.0)")
    chlorophyll_suitability: float = Field(..., description="Chlorophyll-a biomass score (0.0 - 1.0)")
    chlorophyll_front_strength: float = Field(..., description="Color gradient frontal score (0.0 - 1.0)")
    oceanographic_support: float = Field(0.0, description="Currents/shelf structure support (0.0 - 1.0)")
    hazard_penalty: float = Field(0.0, description="Deduction from adverse waves, winds, or cyclones (0.0 - 1.0)")
    raw_weighted_score: float = Field(..., description="Weighted composite score before penalty")
    final_score: float = Field(..., description="Net PFZ score clamped to [0.0, 1.0]")
    weights_used: Dict[str, float] = Field(..., description="Explicit weights configured for each component")

class ConfidenceBreakdown(BaseModel):
    """
    Independent confidence metric separated from the suitability score.
    Section 21 requirement: Based on coverage, sensor quality, and variable agreement.
    """
    overall_confidence_percent: float = Field(..., description="Confidence percentage (0 - 100%)")
    confidence_level: str = Field("MODERATE", description="Categorical rating: HIGH, MODERATE, LOW")
    data_coverage_percent: float = Field(..., description="Percentage of valid unmasked ocean pixels in ROI")
    supporting_variables_count: int = Field(..., description="Number of independent real sensors supporting candidate")
    sensor_provenance: List[str] = Field(default_factory=list, description="List of verified sensors used")
    temporal_alignment: str = Field(..., description="Acquisition freshness / temporal latency status")
    cloud_contamination_percent: float = Field(0.0, description="Percentage of masked cloud/nodata in ROI")
    explanation: str = Field(..., description="Transparent narrative explaining why this confidence was assigned")

class CandidatePolygon(BaseModel):
    """
    Spatial geometry representing the candidate region.
    Level 3 of candidate hierarchy (Section 10).
    """
    coordinates: List[List[float]] = Field(..., description="GeoJSON polygon exterior ring [[lon, lat], ...]")
    bounding_box: List[float] = Field(..., description="[min_lat, min_lon, max_lat, max_lon]")
    area_sq_km: float = Field(..., description="Estimated surface area in square kilometers")
    cell_count: int = Field(..., description="Number of contiguous analytical raster cells in cluster")

class PFZCandidate(BaseModel):
    """
    Comprehensive PFZ candidate model adhering to Section 4 & 10 requirements.
    """
    candidate_id: str = Field(..., description="Unique deterministic identifier for the candidate zone")
    name: str = Field(..., description="Human-readable geographic/oceanographic name")
    result_type: PFZResultType = Field(PFZResultType.MODEL_DERIVED_PFZ)
    centroid_lat: float = Field(..., description="Latitude of candidate centroid")
    centroid_lon: float = Field(..., description="Longitude of candidate centroid")
    distance_km: Optional[float] = Field(None, description="Geodesic distance from query reference point in km")
    bearing_deg: Optional[float] = Field(None, description="Compass bearing from reference point in degrees")
    geometry: CandidatePolygon = Field(..., description="Spatial extent of the candidate zone")
    
    # Environmental Features
    sst_mean_c: Optional[float] = Field(None, description="Mean Sea Surface Temperature in °C")
    sst_gradient_max_c_per_km: Optional[float] = Field(None, description="Maximum thermal gradient magnitude in °C/km")
    chlorophyll_mean_mg_m3: Optional[float] = Field(None, description="Mean Chlorophyll-a in mg/m³")
    chlorophyll_gradient_max_mg_m3_per_km: Optional[float] = Field(None, description="Maximum color gradient magnitude")
    front_strength: float = Field(..., description="Normalized multi-variable frontal coincidence strength [0-1]")
    
    # Atmospheric / Marine Conditions
    wave_height_m: Optional[float] = Field(None, description="Significant wave height (Hs) in meters")
    wind_speed_knots: Optional[float] = Field(None, description="Wind speed in knots")
    current_velocity_ms: Optional[float] = Field(None, description="Surface current velocity in m/s")
    bathymetry_depth_m: Optional[float] = Field(None, description="Estimated bathymetric ocean depth in meters")
    
    # Scoring & Classification
    suitability: SuitabilityBreakdown = Field(..., description="Inspectable environmental suitability decomposition")
    pfz_score: float = Field(..., description="Net PFZ candidate score (0.0 to 1.0)")
    confidence: ConfidenceBreakdown = Field(..., description="Independent data-driven confidence model")
    hazard_status: EnvironmentalHazardStatus = Field(..., description="Fused environmental hazard state")
    hazard_penalties_applied: List[str] = Field(default_factory=list, description="Inspectable list of hazard penalties")
    
    # Metadata & Provenance
    temporal_validity: str = Field(..., description="Time window for which this candidate is scientifically valid")
    source_timestamps: Dict[str, str] = Field(default_factory=dict, description="Source-specific acquisition timestamps")
    provenance: Dict[str, Any] = Field(default_factory=dict, description="Complete provenance and dataset citations")
    derivation_method: str = Field(..., description="Summary of derivation technique (e.g. Coincident SST-Chl Front)")
    limitations: List[str] = Field(default_factory=list, description="Truthful caveats, data gaps, or sensor assumptions")

class PFZAnalysisResponse(BaseModel):
    """
    Standard response payload for PFZ analysis and discovery.
    Section 31 requirement.
    """
    status: str = Field("OK", description="Status code: OK, UNAVAILABLE, FUTURE_EO_UNAVAILABLE")
    analysis_type: PFZResultType = Field(PFZResultType.MODEL_DERIVED_PFZ)
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    time_window: Dict[str, Any] = Field(default_factory=dict)
    region: Dict[str, Any] = Field(default_factory=dict)
    candidates_count: int = Field(0)
    candidates: List[PFZCandidate] = Field(default_factory=list)
    top_candidate: Optional[PFZCandidate] = Field(None)
    environmental_summary: Dict[str, Any] = Field(default_factory=dict)
    active_hazards: List[str] = Field(default_factory=list)
    provenance: List[Dict[str, Any]] = Field(default_factory=list)
    limitations: List[str] = Field(default_factory=list)
    ml_status: str = Field("ML was not claimed because validated training data were unavailable.")
